apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: clankerbot
  labels:
    app: clankerbot
    version: v0.2.1
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: clankerbot
