{{- if or .Values.secrets.CLOCKIFY_API_KEY .Values.secrets.WEBHOOK_SHARED_SECRET .Values.secrets.DEEPSEEK_API_KEY -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clankerbot.fullname" . }}
  labels:
    {{- include "clankerbot.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.CLOCKIFY_API_KEY }}
  CLOCKIFY_API_KEY: {{ .Values.secrets.CLOCKIFY_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.WEBHOOK_SHARED_SECRET }}
  WEBHOOK_SHARED_SECRET: {{ .Values.secrets.WEBHOOK_SHARED_SECRET | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.DEEPSEEK_API_KEY }}
  DEEPSEEK_API_KEY: {{ .Values.secrets.DEEPSEEK_API_KEY | b64enc | quote }}
  {{- end }}
{{- end }}
